targets:
  $default:
    sources:
      include:
        - $package$
        - lib/**
        - assets/**
      exclude:
        - test/**
        - web/**
        - android/**
        - ios/**
        - macos/**
        - linux/**
        - windows/**
